### ISSUE TITLE
[OTHER] Ajouter route

### ISSUE THREAD

**Issue by consithe1** [TC-netw4ppl/website#112]
**Quel est le but de mon issue ?**
Ajouter une route

JP : "Routes :je crois qu’on peut additionner d’autres routes pour qu’elle soient plus précises. Par exemple il y a deux routes pour les Canaries et après multiples en Méditerranée. Au moins pour le moment on doit ajouter Canary Islands"

**Comment by mathisfchx** [comment]
#145
