### ISSUE TITLE
Aspects of the objects

### ISSUE THREAD

**Issue by mathisfchx** [TC-netw4ppl/website#118]
**Si la requête est associée à un problème, merci de le préciser.**
Ø

**Description de la solution souhaitée**
associer un item avec un aspect.
Table d'association objet <-> aspect

**Piste de résolution**
Ø

**Informations supplémentaires**
Ø

**Comment by lduf** [comment]
Utiliser la liste Role pour y associer une couleur et une forme potentiellement

**Comment by lduf** [comment]
P1
