### ISSUE TITLE
[MR Map] Map into MR detail

### ISSUE THREAD

**Issue by lduf** [TC-netw4ppl/website#120]
**Si la requête est associée à un problème, merci de le préciser.**
Ø

**Description de la solution souhaitée**

Show the route of the person on a map
Affichage d'une MAP dans le detail de MR pour afficher des points importants

**Piste de résolution**
À partir des lieux déterminer les coordonnées et les display dans une map (voir openStreetView)

**Informations supplémentaires**
Ø

**Comment by mathisfchx** [comment]
Résumé :
Ajout d'une map pour visualiser la position des différents cas.
Historique des positions (vient de là, vu ici, va là)
Recherche de personnes sur une map
Trajet emprunté
