### ISSUE TITLE
[F_Manag] List Edition

### ISSUE THREAD

**Issue by mathisfchx** [TC-netw4ppl/website#145]
This feature should allow the user to create/edit the list.
e.g add a new route

**Comment by lduf** [comment]
Scaffolding done, #203, still have lot of thing to do, such as : handle the model, ...

**Comment by lduf** [comment]
to create a list should create a new model, a new migration, ....

Check if we can create custom artisan function like 

`php artisan make:list name`

This function should create a new model extending ListControl and could create the migration based on args

**Comment by lduf** [comment]
[https://www.educative.io/answers/how-to-create-a-custom-artisan-command-in-laravel](https://www.educative.io/answers/how-to-create-a-custom-artisan-command-in-laravel
)

**Comment by lduf** [comment]
[ ] rename listcontrol to list can be a good thing to make the global project more comprehensive
