### ISSUE TITLE
[DOC] ReadMe V2

### ISSUE THREAD

**Issue by mathisfchx** [TC-netw4ppl/website#200]
**Que manque-t-il dans la documentation ?**
readme V2 : 
- Easy tutorial to setup local dev with docker and mysql
- More detailled info about files

**Comment by mathisfchx** [comment]
install composer 2
install php8
composer update -W

**Comment by mathisfchx** [comment]
First : "composer diagnose" to see if problems
+ Things like : 
- sudo apt-get install php-curl
- sudo apt-get install php8.1-xml
- sudo apt-get install php-dom
- sudo apt-get install php-zip
...

**Comment by lduf** [comment]
[Utiliser portainer sur votre machine.md](https://github.com/TC-netw4ppl/website/files/9682118/Utiliser.portainer.sur.votre.machine.md)

**Comment by lduf** [comment]
API doc available here : [https://documenter.getpostman.com/view/15399454/2s83tJGAMW](https://documenter.getpostman.com/view/15399454/2s83tJGAMW)
