### ISSUE TITLE
can be deleted 'nullable' is a non sense

### ISSUE THREAD

**Issue by lduf** [TC-netw4ppl/website#212]
can be deleted 'nullable' is a non sense

_Originally posted by @lduf in https://github.com/TC-netw4ppl/website/pull/203#discussion_r983624874_

**Comment by mathisfchx** [comment]
`"validation_laravel": "nullable|regex:/^[A-Z]{3}-[0-9]{6}$/"`

**Comment by lduf** [comment]
fixed #241
