### ISSUE TITLE
[NEW FEATURE]enable mail on laravel

### ISSUE THREAD

**Issue by lduf** [TC-netw4ppl/website#218]
**If the request is associated with a problem, please specify it.**
Add email support to the webapp

**Description of the desired solution**
Ø

**Resolution path**
Ø

**Additional information**
Ø

**Comment by mathisfchx** [comment]
account verification, password reset,

**Comment by lduf** [comment]
bon relou, ça m'a pris la journée pour install un serveur mail et ça ne marche pas. Grrr
-> Debug try to do list : 

- try another smtp client 
- if same bug, check codes ....
- Else check poste.io issues (ssl, ...)

**Comment by lduf** [comment]
Done ;)
