### ISSUE TITLE
[NEW FEATURE] New Role create and core usage

### ISSUE THREAD

**Issue by mathisfchx** [TC-netw4ppl/website#233]
**If the request is associated with a problem, please specify it.**
-> new User create view with checkboxs
-> new table with all the rights of the roles
-> in policies, check the rights one per one (and not the name)

**Comment by lduf** [comment]
Piste de résolution : 

- [ ] lister les routes possibles (filtrer sur celle qui nous intéressent vraiment
- [ ] regrouper avec un policy route 
*Exemple :* 

```
#  | route | policy_route 
id1 | person.update | person.update
id2 | person.edit | person.update 
```
On pourrait utiliser cette fonction pour mapper entre route et policy route


```
getPolicyRouteNameFromRouteName($route_name){
  $route = explode(".", $route_name);
  $policyRouteName = [
    "create" => "store",
    "store" => "store",
    "index" => "view_any",  
    …
  ];


  return $route[0].".".$policyRouteName[$route[1]];
}
```

- [ ] Dans les views faire les check box en fonction de policy_route et save dans la pivot en faisant un where sur policy_route

**Comment by lduf** [comment]
Will fix #143, #122
