### ISSUE TITLE
[OTHER] Roles crew linked by filtering groups of roles in the dropdown

### ISSUE THREAD

**Issue by mathisfchx** [TC-netw4ppl/website#242]
**What is the purpose of this issue ?**
Making roles pseudo-cew-linked

: by filtering the roles by teams inside the dropdown

**Comment by lduf** [comment]
[https://laracasts.com/discuss/channels/laravel/livewire-multiple-select](https://laracasts.com/discuss/channels/laravel/livewire-multiple-select)
