### ISSUE TITLE
[BUG] Even if the field is disabled, the android app try to get it through the API

### ISSUE THREAD

**Issue by mathisfchx** [TC-netw4ppl/website#319]
**Description of the bug**
Even if the field is disabled, the android app try to get it through the API
=> if there is a bug, we cannot bypass it

**Comment by lduf** [comment]
@mathisfchx I need more details

**Comment by mathisfchx** [comment]
exemple :
I have 3 field, one of them implements the **List Routes** but the field is **Disabled** :
The API will send me the content of the route list even if i don't need it.
