### ISSUE TITLE
[NEW FEATURE] back geolocalisation

### ISSUE THREAD

**Issue by skeayz** [TC-netw4ppl/website#351]
**Description of the desired solution**
Build  back for coordinates 

**Resolution path**
If you have an idea of how to do it, you can give us some hints here!

**If the request is associated with a problem, please specify it.**
Give a quick description of the problem or what it frustrates you in the application.
You can associate a [BUG] issue to it.

**Additional information**
You can add anything you want here!

**Comment by AntoinePiron** [comment]
#124
